name: CI/CD

on:
  push:
    branches:
      - master

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python 3.8
      uses: actions/setup-python@v1
      with:
        python-version: 3.8
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install pylint
    - name: Analysing the code with pylint
      run: |
        find . -name '*.py' -exec pylint {} \;
# Uncomment and customize the following sections as needed

# build:
#   runs-on: ubuntu-latest
# 
#   steps:
#     - name: Checkout code
#       uses: actions/checkout@v2
# 
#     - name: Building
#       run: docker-compose build
# 
# unit_test:
#   runs-on: ubuntu-latest
# 
#   steps:
#     - name: Checkout code
#       uses: actions/checkout@v2
# 
#     - name: Unit Testing
#       run: docker-compose run app <unit_test_command>
# 
# integration_test:
#   runs-on: ubuntu-latest
# 
#   steps:
#     - name: Checkout code
#       uses: actions/checkout@v2
# 
#     - name: Integration Testing
#       run: docker-compose run app <integration_test_command>
# 
# code_coverage:
#   runs-on: ubuntu-latest
# 
#   steps:
#     - name: Checkout code
#       uses: actions/checkout@v2
# 
#     - name: Code Coverage
#       run: docker-compose run app <code_coverage_command>
# 
# container_scan:
#   runs-on: ubuntu-latest
# 
#   steps:
#     - name: Checkout code
#       uses: actions/checkout@v2
# 
#     - name: Pushing to Registry
#       run: docker-compose push
# 
#     - name: Container Scan
#       run: docker scan --severity <scan_severity> <image_name>
# 
# deploy:
#   runs-on: ubuntu-latest
# 
#   steps:
#     - name: Checkout code
#       uses: actions/checkout@v2
# 
#     - name: Deployment
#       run: docker-compose up -d
